export interface SourceAtlasText { en: string; zh: string; }
export type SourceAtlasTrack = 'difference-engine-no-2' | 'bush-differential-analyzer' | 'curta' | 'analytical-engine';
export type SourceAtlasClaimType = 'H' | 'R';
export type SourceAtlasEvidenceStrength = 'E1' | 'E2' | 'E3';
export type SourceAtlasAccessKind = 'direct archive record' | 'direct catalog' | 'institutional reconstruction' | 'institutional historical study' | 'bibliographic-only' | 'direct primary facsimile' | 'specialist-hosted primary facsimile' | 'specialist transcription' | 'reconstruction documentation';

export interface NamedMachineSourceAnchor {
  id: string;
  track: SourceAtlasTrack;
  generation: SourceAtlasText;
  sourceTitle: string;
  institution: string;
  sourceUrl: string;
  recordIdentifier: string;
  claimType: SourceAtlasClaimType;
  evidenceStrength: SourceAtlasEvidenceStrength;
  accessKind: SourceAtlasAccessKind;
  inspectedDate: '2026-09-01' | '2026-09-02';
  supports: readonly SourceAtlasText[];
  notEstablished: readonly SourceAtlasText[];
  researchNoteAnchor: string;
  fullFacsimileInspected?: boolean;
  pageFigureAnchors?: readonly string[];
  documentRole?: 'patent' | 'operator manual' | 'service manual' | 'historical publication' | 'archive drawing' | 'technical description' | 'emulator documentation';
  accessHost?: string;
}

const DE_OPEN = [{ en: 'exact tooth counts, linkage paths, synchronization, force/load, tolerances, manufacturing method, or repository event order', zh: '确切齿数、连杆路径、同步、力/负载、公差、制造方法或本站事件顺序' }];
const BUSH_OPEN = [{ en: 'the repository A+B → integrator → tracer wiring, scale values, timing, torque, efficiency, tolerances, or full-machine geometry', zh: '本站 A+B → 积分器 → 描迹器的连接、比例值、时序、扭矩、效率、公差或整机几何' }];

export const NAMED_MACHINE_SOURCE_ANCHORS: readonly NamedMachineSourceAnchor[] = [
  {
    id: 'de2-technical-description-2020', track: 'difference-engine-no-2', generation: { en: 'modern institutional reconstruction, completed 2002', zh: '现代机构复原，2002 年完成' }, sourceTitle: "Charles Babbage's Difference Engine No. 2: Technical Description", institution: 'Science Museum', accessHost: 'Science Museum PDF host', sourceUrl: 'https://www.sciencemuseum.org.uk/sites/default/files/2023-09/DE2_Technical_Description.pdf', recordIdentifier: 'Doron D. Swade, March 2020; 232-page PDF', claimType: 'R', evidenceStrength: 'E2', accessKind: 'institutional reconstruction', inspectedDate: '2026-09-01', documentRole: 'technical description', fullFacsimileInspected: true, pageFigureAnchors: ['p. i (scope and reconstruction boundary)', 'pp. 4–9 (sources and modern manufacturing drawings)', 'pp. 21–24, Figs. 3.2–3.4 (F/385/1 and A/171 interpretation)', 'pp. 33–45, Figs. 3.16–3.20 (warning/carry/restoration)', 'pp. 49–54, Figs. 4.1–4.3 (output transfer)', 'pp. 83–85 (modern paper-system additions)', 'pp. 187–188 (original versus reconstructed lock timing)', 'pp. 212–218 (archive/construction drawing appendices)'], researchNoteAnchor: 'research/difference-engine-source-map.md#directly-inspected-institutional-technical-description',
    supports: [{ en: 'institutional interpretation of the calculating cycle and calculated-result transfer to printing/stereotype roles, with modern design decisions and modifications explicitly identified', zh: '机构对计算周期及结果转入打印/铸版职责的解释，并明确标出现代设计决策与修改' }],
    notEstablished: [{ en: 'a Babbage-lifetime built artifact, or Babbage-specified manufacturing tolerances, materials, exact lock phasing, modern fixes, or repository event order', zh: 'Babbage 生前建成的实物，或由 Babbage 规定的制造公差、材料、确切锁定相位、现代修正或本站事件顺序' }],
  },
  {
    id: 'bab-b-001', track: 'difference-engine-no-2', generation: { en: 'Babbage DE2 design, 1847–1848', zh: 'Babbage 差分机二号设计，1847–1848' }, sourceTitle: 'Elevation of Difference Engine No.2', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110117998/elevation-of-difference-engine-no-2', recordIdentifier: 'BAB/B/001 / aa110117998', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', documentRole: 'archive drawing', fullFacsimileInspected: false, pageFigureAnchors: [], researchNoteAnchor: 'research/difference-engine-source-map.md#general-design-and-calculationaddition-drive-subjects',
    supports: [{ en: 'one-sheet elevation-record identity, 1847–1848 date, Babbage maker attribution, open access, and catalogued DE2 elevation subject', zh: '单张立面图档案身份、1847–1848 年代、Babbage 制作者归属、开放访问及目录所述差分机二号立面主题' }],
    notEstablished: [{ en: 'tooth counts, linkage interpretation, timing, materials, tolerances, construction choices, or every interpretation in the modern technical description', zh: '齿数、连杆解释、时序、材料、公差、建造选择，或现代技术说明中的全部解释' }],
  },
  {
    id: 'babbage-papers-index', track: 'difference-engine-no-2', generation: { en: 'Babbage archive, 1821–1905', zh: 'Babbage 档案，1821–1905' }, sourceTitle: 'The Babbage Papers', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110000003/the-babbage-papers', recordIdentifier: 'BAB / aa110000003', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/difference-engine-source-map.md#4-babbage-papers-drawing-and-notation-anchors',
    supports: [{ en: 'archive identity, 1821–1905 date span, open access, extent, and the existence of notebooks, engineering drawings, and motion notations', zh: '档案身份、1821–1905 年代范围、开放访问、规模，以及笔记本、工程图和运动记法的存在' }],
    notEstablished: DE_OPEN,
  },
  {
    id: 'bab-a-171', track: 'difference-engine-no-2', generation: { en: 'Babbage DE2 design', zh: 'Babbage 差分机二号设计' }, sourceTitle: 'Addition carriage and mode of driving the axes of Difference Engine No. 2', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110000314/addition-carriage-and-mode-of-driving-the-axes-of-difference-engine-no-2', recordIdentifier: 'BAB/A/171 / aa110000314', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/difference-engine-source-map.md#4-babbage-papers-drawing-and-notation-anchors',
    supports: [{ en: 'one-sheet archive identity and catalogued calculation/addition-carriage drive subject', zh: '单张档案身份以及目录所述的计算/加法进位架驱动主题' }],
    notEstablished: [{ en: 'printer timing, printer geometry, exact drive linkage, or historical operating sequence', zh: '打印时序、打印机构几何、确切驱动连杆或历史操作顺序' }],
  },
  {
    id: 'bab-b-013', track: 'difference-engine-no-2', generation: { en: 'Babbage DE2 tracing, 1847–1848', zh: 'Babbage 差分机二号描图，1847–1848' }, sourceTitle: 'End view of inking printing paper and stereotyping apparatus; tracing of BAB/A/172', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110000343', recordIdentifier: 'BAB/B/013 / aa110000343', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/difference-engine-source-map.md#4-babbage-papers-drawing-and-notation-anchors',
    supports: [{ en: 'tracing identity, 1847–1848 date, and catalogued inking/printing/paper/stereotyping subject', zh: '描图身份、1847–1848 年代及目录所述着墨/打印/纸张/铸版主题' }], notEstablished: [...DE_OPEN, { en: 'that the complete apparatus was built in Babbage’s lifetime', zh: '完整机构在 Babbage 生前建成' }],
  },
  {
    id: 'bab-b-014', track: 'difference-engine-no-2', generation: { en: 'Babbage DE2 tracing, 1847–1848', zh: 'Babbage 差分机二号描图，1847–1848' }, sourceTitle: 'Plan of inking, printing and stereotype apparatus; tracing of BAB/A/173', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110000344', recordIdentifier: 'BAB/B/014 / aa110000344', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/difference-engine-source-map.md#4-babbage-papers-drawing-and-notation-anchors',
    supports: [{ en: 'tracing identity, 1847–1848 date, and catalogued plan subject', zh: '描图身份、1847–1848 年代及目录所述平面图主题' }], notEstablished: [...DE_OPEN, { en: 'that the complete apparatus was built in Babbage’s lifetime', zh: '完整机构在 Babbage 生前建成' }],
  },
  {
    id: 'bab-a-178-3', track: 'difference-engine-no-2', generation: { en: 'Babbage DE2 notation, August 1848', zh: 'Babbage 差分机二号记法，1848 年 8 月' }, sourceTitle: 'Motions of the printing apparatus', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110000324', recordIdentifier: 'BAB/A/178/3 / aa110000324', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/difference-engine-source-map.md#4-babbage-papers-drawing-and-notation-anchors',
    supports: [{ en: 'one-sheet notation identity, date, dimensions, and catalogued printing-apparatus motion subject', zh: '单张记法的身份、日期、尺寸及目录所述打印机构运动主题' }], notEstablished: DE_OPEN,
  },
  {
    id: 'de2-reconstruction-1991-2002', track: 'difference-engine-no-2', generation: { en: 'modern institutional reconstruction', zh: '现代机构复原' }, sourceTitle: "Babbage's Difference Engine No 2, 2002", institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/objects/co62748', recordIdentifier: '1992-556 / co62748', claimType: 'R', evidenceStrength: 'E2', accessKind: 'institutional reconstruction', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/difference-engine-source-map.md#3-difference-engine-no-2-design-versus-reconstruction',
    supports: [{ en: 'Science Museum construction: calculating section completed 1991, printing mechanism added 2002; DE2 was not built in Babbage’s lifetime', zh: 'Science Museum 建造：计算部分 1991 年完成，打印机构 2002 年加入；差分机二号未在 Babbage 生前建成' }],
    notEstablished: [{ en: 'a Babbage-lifetime artifact or automatic identity between reconstructed choices and every original drawing detail', zh: 'Babbage 生前实物，或复原选择与每一项原图细节自动等同' }],
  },
  {
    id: 'scheutz-1853-smithsonian', track: 'difference-engine-no-2', generation: { en: 'built Scheutz printing difference engine, 1853', zh: '1853 年建成的 Scheutz 打印差分机' }, sourceTitle: 'Scheutz Difference Engine', institution: 'Smithsonian / National Museum of American History', accessHost: 'NMAH catalog + Smithsonian IIIF manifest', sourceUrl: 'https://americanhistory.si.edu/collections/object/nmah_997042', recordIdentifier: 'MA.323659 / nmah_997042; made 1853; 56 × 170 × 58 cm', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-02', documentRole: 'historical publication', fullFacsimileInspected: false, pageFigureAnchors: ['NMAH object record', 'IIIF SIA-89-22028: one 3000×1946 object-image canvas'], researchNoteAnchor: 'research/difference-engine-source-map.md#smithsonian-1853-built-machine',
    supports: [{ en: 'surviving built printing calculator object, Georg and Edvard Scheutz maker identity, 1853 Stockholm date/place, materials/dimensions, Paris 1855 exhibition, Dudley sale and U.S. government-contract catalog context', zh: '存世建成的打印计算器实物、Georg 与 Edvard Scheutz 制作者、1853 年 Stockholm 日期/地点、材料/尺寸、1855 Paris 展览、售予 Dudley 及美国政府合同的目录语境' }],
    notEstablished: [{ en: 'internal geometry, printer timing, tooth counts, throughput, reliability/error rate, government-contract workflow, Babbage-printer identity, or repository P/M output-event identity', zh: '内部几何、打印时序、齿数、吞吐量、可靠性/错误率、政府合同流程、与 Babbage 打印机构相同，或与本站 P/M 输出事件相同' }],
  },
  {
    id: 'scheutz-1857-drawings-smithsonian', track: 'difference-engine-no-2', generation: { en: 'Scheutz operational drawing set, ca. 1857', zh: '约 1857 年 Scheutz 操作图纸组' }, sourceTitle: 'Sheet of Drawings of the Scheutz Difference Engine', institution: 'Smithsonian / National Museum of American History', accessHost: 'NMAH catalog + Smithsonian IIIF manifest', sourceUrl: 'https://americanhistory.si.edu/collections/object/nmah_1005138', recordIdentifier: '1988.0798.01 / nmah_1005138; ca. 1857; 14 figures; catalog says patent No. 2214', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-02', documentRole: 'archive drawing', fullFacsimileInspected: false, pageFigureAnchors: ['catalog: Fig. 1 through Figure 14', 'IIIF SIA-2002-16607: one 3000×1970 drawing-image canvas'], researchNoteAnchor: 'research/difference-engine-source-map.md#smithsonian-ca-1857-operational-drawing-set',
    supports: [{ en: 'catalogued ca. 1857 drawing object and its instruction provenance: the set plus an unexposed letter accompanied the Albany shipment; catalog says figures are similar to but not identical with final patent specifications and numbered differently', zh: '约 1857 年图纸实物及其目录所述操作说明来源：该图纸组与一封未公开信件随 Albany 装运；目录称图形与最终专利说明相似但不相同，编号也不同' }],
    notEstablished: [{ en: 'letter content beyond the catalog summary, exact geometry, equivalence with patent figures, why the catalog says No. 2214 despite independent contemporary/patent No. 2216 evidence, Babbage-printer architecture, or repository P/M output-event identity', zh: '超出目录摘要的信件内容、确切几何、与专利图等同、为何目录写 2214 而独立同期/专利证据写 2216、Babbage 打印机构或本站 P/M 输出事件身份' }],
  },
  {
    id: 'scheutz-patent-list-1855', track: 'difference-engine-no-2', generation: { en: 'contemporary British patent list, 1855', zh: '1855 年英国同期专利列表' }, sourceTitle: 'Weekly List of Patents Sealed', institution: 'Journal of the Society of Arts', accessHost: 'public-domain JSTOR/Internet Archive scan via Wikimedia Commons', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Journal_of_the_Society_of_Arts,_Vol._3,_no._126_(IA_jstor-41323556).pdf', recordIdentifier: 'vol. III no. 126, 20 April 1855, printed p. 393; sealed 13 April; Scheutz No. 2216', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct primary facsimile', inspectedDate: '2026-09-02', documentRole: 'historical publication', fullFacsimileInspected: true, pageFigureAnchors: ['printed p. 393: entry 2216 between adjacent 2208 and 2304'], researchNoteAnchor: 'research/difference-engine-source-map.md#contemporary-patent-identity-no-2216',
    supports: [{ en: 'independent contemporary publication identifies George and Edward Scheutz patent No. 2216 and its calculating-plus-printing title; the Smithsonian drawing catalog’s No. 2214 wording remains separately visible', zh: '独立同期出版物确认 George 与 Edward Scheutz 的 2216 号专利及计算兼打印标题；Smithsonian 图纸目录的 2214 表述仍单独保留' }],
    notEstablished: [{ en: 'that Smithsonian No. 2214 is institutionally established as a typo, patent geometry, identity with the as-built machine or ca. 1857 figures, printer timing/performance, Babbage architecture, or repository P/M output events', zh: 'Smithsonian 的 2214 已由机构确认是笔误、专利几何、与实物或约 1857 图纸等同、打印时序/性能、Babbage 架构或本站 P/M 输出事件' }],
  },
  {
    id: 'scheutz-royal-society-1855', track: 'difference-engine-no-2', generation: { en: 'Royal Society committee examination, 1855', zh: '1855 年 Royal Society 委员会检验报告' }, sourceTitle: 'Report of a Committee appointed by the Council to examine the Calculating Machine of M. Scheutz', institution: 'Proceedings of the Royal Society of London', accessHost: 'public-domain JSTOR/Internet Archive scan via Wikimedia Commons', sourceUrl: 'https://commons.wikimedia.org/wiki/File:Report_of_a_Committee_Appointed_by_the_Council_to_Examine_the_Calculating_Machine_of_M._Scheutz_(IA_jstor-111836).pdf', recordIdentifier: 'Proceedings vol. 7, printed pp. 499–509; Stokes, Miller, Wheatstone, Willis', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct primary facsimile', inspectedDate: '2026-09-02', documentRole: 'historical publication', fullFacsimileInspected: true, pageFigureAnchors: ['pp. 499–502 role/capacity/calculation/output', 'pp. 503–507 mathematical limits', 'pp. 507–508 reverse-output limitation and committee utility assessment'], researchNoteAnchor: 'research/difference-engine-source-map.md#royal-society-committee-examination-1855',
    supports: [{ en: 'committee-reported examination: four difference orders and fifteen-digit internal values, eight printed function digits, alternating addition motions, calculated value/argument impressed into lead for stereotype plates, and explicit mathematical/printing limitations', zh: '委员会检验报告：四阶差分与十五位内部数值、打印函数前八位、交替加法运动、将计算值/自变量压入铅板以制铸版，并明确讨论数学与打印限制' }],
    notEstablished: [{ en: 'exact surviving-object geometry, patent/as-built identity, printer synchronization, controlled speed/reliability/error benchmarks, universal lifetime performance, Babbage-printer equivalence, or repository P/M timing', zh: '存世实物确切几何、专利与实物等同、打印同步、受控速度/可靠性/误差基准、全生命周期普遍性能、与 Babbage 打印机构等同或本站 P/M 时序' }],
  },
  {
    id: 'scheutz-merzbach-1977', track: 'difference-engine-no-2', generation: { en: 'Smithsonian historical synthesis and reproduced patent, 1977', zh: '1977 年 Smithsonian 历史研究及专利复刻' }, sourceTitle: 'Georg Scheutz and the First Printing Calculator', institution: 'Smithsonian Institution Press / GovInfo access', accessHost: 'U.S. Government GovInfo PDF', sourceUrl: 'https://www.govinfo.gov/content/pkg/GOVPUB-SI-PURL-gpo20587/pdf/GOVPUB-SI-PURL-gpo20587.pdf', recordIdentifier: 'Smithsonian Studies in History and Technology no. 36; 84-page PDF; Appendix I identifies British Patent A.D. 1854 No. 2216', claimType: 'H', evidenceStrength: 'E2', accessKind: 'institutional historical study', inspectedDate: '2026-09-02', documentRole: 'historical publication', fullFacsimileInspected: false, pageFigureAnchors: ['p. 13 completion', 'pp. 19–21 patent/Paris chronology', 'pp. 26–29 Albany/use/contract', 'Appendix I pp. 43–55 reproduced patent No. 2216'], researchNoteAnchor: 'research/difference-engine-source-map.md#merzbach-1977-institutional-study-and-reproduced-patent',
    supports: [{ en: 'institutional chronology of 1853 completion, 1854–1855 patent process, Paris 1855, Albany 1857 and bounded 1858 work; Appendix I separately reproduces identified patent No. 2216', zh: '机构研究所述 1853 完工、1854–1855 专利过程、1855 Paris、1857 Albany 及有限的 1858 工作；附录 I 另行复刻具名专利 2216' }],
    notEstablished: [{ en: 'that synthesis prose is primary E1 evidence, that the Smithsonian 14-figure sheet equals patent figures, exact printer synchronization/performance, Babbage-printer architecture, or repository P/M event timing', zh: '研究叙述本身属于 E1 一手证据、Smithsonian 14 图纸组等同专利图、确切打印同步/性能、Babbage 打印机构或本站 P/M 事件时序' }],
  },
  {
    id: 'smithsonian-da-group', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer and later generations', zh: 'MIT 原始分析机及后续世代' }, sourceTitle: 'Differential Analyzer Parts and Documentation', institution: 'Smithsonian/NMAH', sourceUrl: 'https://americanhistory.si.edu/collections/object-groups/mechanical-integrators/differential-analyzers', recordIdentifier: 'NMAH object group', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#2-smithsoniannational-museum-of-american-history-records',
    supports: [{ en: 'group context distinguishes the ca. 1930 MIT analyzer, improved MIT machine, and postwar GE/UCLA components', zh: '馆藏组语境区分约 1930 年 MIT 分析机、改进型 MIT 机器及战后 GE/UCLA 部件' }], notEstablished: BUSH_OPEN,
  },
  {
    id: 'bush-input-1983-3002-01', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer, ca. 1930', zh: 'MIT 原始分析机，约 1930' }, sourceTitle: 'Input Table Carriage from the Bush Differential Analyzer', institution: 'Smithsonian/NMAH', sourceUrl: 'https://www.si.edu/object/input-table-carriage-bush-differential-analyzer%3Anmah_693232', recordIdentifier: '1983.3002.01 / nmah_693232', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#2-smithsoniannational-museum-of-american-history-records',
    supports: [{ en: 'curve-following pointer motion was transported by a shaft to an appropriate machine part', zh: '沿曲线移动的指针运动由轴传送到机器的相应部分' }], notEstablished: BUSH_OPEN,
  },
  {
    id: 'bush-adder-1983-3002-02', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer, ca. 1930', zh: 'MIT 原始分析机，约 1930' }, sourceTitle: 'Adder or Differential Gear from the Bush Differential Analyzer', institution: 'Smithsonian/NMAH', sourceUrl: 'https://www.si.edu/object/nmah_693233', recordIdentifier: '1983.3002.02 / nmah_693233', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#2-smithsoniannational-museum-of-american-history-records',
    supports: [{ en: 'a differential gear combined rotations of shafts a and b so shaft c represented their sum', zh: '差动齿轮组合 a、b 两轴转动，使 c 轴表示其和' }], notEstablished: BUSH_OPEN,
  },
  {
    id: 'bush-integrator-ma-314824', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer, ca. 1930', zh: 'MIT 原始分析机，约 1930' }, sourceTitle: 'Integrator Unit from Bush Differential Analyzer', institution: 'Smithsonian/NMAH', sourceUrl: 'https://www.si.edu/object/integrator-unit-bush-differential-analyzer%3Anmah_1215155', recordIdentifier: 'MA.314824 / nmah_1215155', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#2-smithsoniannational-museum-of-american-history-records',
    supports: [{ en: 'the catalogued box contains two of six original integrators associated with the MIT analyzer', zh: '目录所载箱体包含与 MIT 分析机相关的六个原始积分器中的两个' }], notEstablished: BUSH_OPEN,
  },
  {
    id: 'bush-tracer-1983-3002-03', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer, ca. 1930', zh: 'MIT 原始分析机，约 1930' }, sourceTitle: 'Carriage and Tracer for an Output Table from the Bush Differential Analyzer', institution: 'Smithsonian/NMAH', sourceUrl: 'https://www.si.edu/object/carriage-and-tracer-output-table-bush-differential-analyzer%3Anmah_693234', recordIdentifier: '1983.3002.03 / nmah_693234', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#2-smithsoniannational-museum-of-american-history-records',
    supports: [{ en: 'result-shaft rotation was transmitted to a tracer that drew results on an output table', zh: '结果轴转动被传送到描迹器，在输出台上绘制结果' }], notEstablished: BUSH_OPEN,
  },
  {
    id: 'bush-frontlash-1983-3002-04', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer, ca. 1930', zh: 'MIT 原始分析机，约 1930' }, sourceTitle: 'Frontlash Unit from the Bush Differential Analyzer', institution: 'Smithsonian/NMAH', sourceUrl: 'https://www.si.edu/object/frontlash-unit-bush-differential-analyzer%3Anmah_693235', recordIdentifier: '1983.3002.04 / nmah_693235', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct catalog', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#2-smithsoniannational-museum-of-american-history-records',
    supports: [{ en: 'museum-described compensation for backlash in a drive between one unit’s output shaft and an adjacent unit’s input shaft', zh: '博物馆所述：补偿一个单元输出轴与相邻单元输入轴之间传动的回差' }],
    notEstablished: [{ en: 'numerical backlash or residual error, exact placement, full-machine wiring, tolerance, efficiency, response time, or torque amplification', zh: '回差或残余误差数值、确切位置、整机连接、公差、效率、响应时间或扭矩放大' }],
  },
  {
    id: 'bush-1931-paper', track: 'bush-differential-analyzer', generation: { en: 'Bush contemporary publication, 1931', zh: 'Bush 同时代论文，1931' }, sourceTitle: 'The Differential Analyzer. A New Machine for Solving Differential Equations', institution: 'Journal of the Franklin Institute / Elsevier DOI record', sourceUrl: 'https://doi.org/10.1016/S0016-0032(31)90616-9', recordIdentifier: 'DOI 10.1016/S0016-0032(31)90616-9; JFI 212(4), 447–488', claimType: 'H', evidenceStrength: 'E1', accessKind: 'bibliographic-only', inspectedDate: '2026-09-01', researchNoteAnchor: 'research/differential-analyzer.md#1-vannevar-bush-1931', fullFacsimileInspected: false, pageFigureAnchors: [],
    supports: [{ en: 'bibliographic identity, author, title, journal, volume/issue, date, and page range', zh: '书目信息：作者、标题、期刊、卷期、日期和页码范围' }],
    notEstablished: [{ en: 'any page quotation, figure-specific geometry, or claim about an unchanged later Differential Analyzer construction', zh: '任何逐页引文、图号级几何或后续微分分析机结构始终不变的说法' }],
  },
  {
    id: 'bush-caldwell-thomas-fermi-1931', track: 'bush-differential-analyzer', generation: { en: 'original MIT analyzer application, 1931', zh: 'MIT 原始分析机应用，1931' }, sourceTitle: 'Thomas-Fermi Equation Solution by the Differential Analyzer', institution: 'Physical Review / American Physical Society', accessHost: 'APS Harvest fulltext service', sourceUrl: 'https://harvest.aps.org/v2/journals/articles/10.1103/PhysRev.38.1898/fulltext', recordIdentifier: 'DOI 10.1103/PhysRev.38.1898; Physical Review 38, 1898–1902', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct primary facsimile', inspectedDate: '2026-09-01', documentRole: 'historical publication', fullFacsimileInspected: true, pageFigureAnchors: ['printed p. 1898 (application, independent check, separate construction-paper boundary)', 'printed p. 1899 (problem procedure)', 'printed pp. 1900–1902, Figs. 1–3 (problem-specific connection diagrams; scales/signs/gear ratios disregarded)', 'printed p. 1902 (independent integration check)'], researchNoteAnchor: 'research/differential-analyzer.md#bush-and-caldwell-1931-directly-inspected-application-paper',
    supports: [{ en: 'an actual 1931 Thomas–Fermi calculation, its stated procedure and independent check, and published problem-specific multiplier/input/integrator/output-table schematic roles', zh: '1931 年实际 Thomas–Fermi 计算、文中所述流程与独立校验，以及针对该问题发表的乘法器/输入台/积分器/输出台示意职责' }],
    notEstablished: [{ en: 'a construction manual, exact shaft routing, placement, scale factors, gear ratios, permanent repository A+B → integrator → tracer wiring, or later analyzer geometry', zh: '建造手册、确切轴路由、布置、比例因子、齿轮比、本站 A+B → 积分器 → 描迹器的永久连接，或后续分析机几何' }],
  },
  {
    id: 'curta-us2525352', track: 'curta', generation: { en: 'Herzstark patented embodiment, filed 1948/granted 1950', zh: 'Herzstark 专利实施例，1948 申请/1950 授权' }, sourceTitle: 'Calculating Machine', institution: 'United States Patent Office', accessHost: 'Google Patents / Google patent PDF host', sourceUrl: 'https://patents.google.com/patent/US2525352A/en', recordIdentifier: 'US 2,525,352; 2 sheets; 5 claims', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct primary facsimile', inspectedDate: '2026-09-01', documentRole: 'patent', fullFacsimileInspected: true, pageFigureAnchors: ['PDF sheets 1–2; specification pp. 1–4; Figures 1–11'], researchNoteAnchor: 'research/curta-source-map.md#1-curt-herzstark-patent-us-2525352',
    supports: [{ en: 'the patented miniature design places result and revolution counting mechanisms around a common driving member; Figures 1–11 and specification pages 1–4 were inspected', zh: '该专利微型设计把结果与转数计数机构布置在共同驱动构件周围；已检查图 1–11 及说明书第 1–4 页' }],
    notEstablished: [{ en: 'identity with every production Type I or Type II machine, exact repository cylinder geometry, operator procedure, or production revision history', zh: '与每一台量产 Type I/II 完全一致、本站圆筒几何、操作程序或量产修订史' }],
  },
  {
    id: 'curta-operator-guide', track: 'curta', generation: { en: 'Contina operator guide covering Models I and II', zh: '涵盖 Model I 与 II 的 Contina 操作指南' }, sourceTitle: 'Your CURTA Calculator', institution: 'Contina, Manufactory of Office and Calculating Machines Ltd., Vaduz/Liechtenstein', accessHost: 'mycurta.com specialist mirror', sourceUrl: 'https://www.mycurta.com/Documents/Curta-User-Guide-Your-CURTA-Calculator-210810.pdf', recordIdentifier: 'English operator guide; 2-page scan; viewer page 1/2 inspected', claimType: 'H', evidenceStrength: 'E1', accessKind: 'specialist-hosted primary facsimile', inspectedDate: '2026-09-01', documentRole: 'operator manual', fullFacsimileInspected: false, pageFigureAnchors: ['viewer page 1 of 2'], researchNoteAnchor: 'research/curta-source-map.md#2-directly-inspected-operator-and-service-facsimiles',
    supports: [{ en: 'operator-facing handle zero-stop, plus/minus position, carriage movement/locking, setting/result/counter roles, clearing control, and stated capacities I 8×6×11 / II 11×8×15', zh: '面向操作者的曲柄零位、加减位置、滑架移动/锁定、设定/结果/计数角色、清零控制，以及所述 I 8×6×11 / II 11×8×15 容量' }],
    notEstablished: [{ en: 'service linkage geometry, equality of all hidden Type I/II parts, issue date/edition not printed on the inspected page, or identity with the repository interlock state machine', zh: '维修连杆几何、Type I/II 所有隐藏零件相同、已检查页未印出的版本日期，或与本站互锁状态机等同' }],
  },
  {
    id: 'curta-type1-service-1967', track: 'curta', generation: { en: 'Curta Model I service document, 1967', zh: 'Curta Model I 维修文档，1967' }, sourceTitle: 'Service-Manual: Curta Calculating Machine, Model I 8×6×11', institution: 'Contina AG, Mauren, Liechtenstein', accessHost: 'mycurta.com specialist mirror', sourceUrl: 'https://www.mycurta.com/Documents/Curta_1_Servivce_Manual_engl.pdf', recordIdentifier: 'English service manual; 59-page scan; issued autumn 1967; cover inspected', claimType: 'H', evidenceStrength: 'E1', accessKind: 'specialist-hosted primary facsimile', inspectedDate: '2026-09-01', documentRole: 'service manual', fullFacsimileInspected: false, pageFigureAnchors: ['viewer cover 1/59'], researchNoteAnchor: 'research/curta-source-map.md#2-directly-inspected-operator-and-service-facsimiles',
    supports: [{ en: 'document identity as a Contina AG English service manual specifically for Model I 8×6×11, issued autumn 1967', zh: '文档身份：Contina AG 英文维修手册，明确对应 Model I 8×6×11，1967 年秋发布' }],
    notEstablished: [{ en: 'operator instructions, Type II construction, full hidden linkage interpretation, or that every Model I production revision is unchanged', zh: '操作指南、Type II 结构、完整隐藏连杆解释，或所有 Model I 量产修订均不变' }],
  },
  {
    id: 'curta-type2-service', track: 'curta', generation: { en: 'Curta Model II replacement-leaf service document', zh: 'Curta Model II 换页式维修文档' }, sourceTitle: 'Servicehandbuch – Service Manual: CURTA Mod. II', institution: 'Contina AG, Vaduz FL', accessHost: 'mycurta.com specialist mirror; index credits Museum Mura source layer', sourceUrl: 'https://www.mycurta.com/Documents/Curta_2_Service_Manual_Curta2_green_e.pdf', recordIdentifier: 'English/German-titled 43-page image-only scan; no cover date/revision/capacity visible', claimType: 'H', evidenceStrength: 'E1', accessKind: 'specialist-hosted primary facsimile', inspectedDate: '2026-09-01', documentRole: 'service manual', fullFacsimileInspected: false, pageFigureAnchors: ['PDF p. 1 cover', 'PDF p. 2 replacement-leaf and Model-I-picture warning', 'PDF p. 6 / leaf N I-a', 'PDF p. 10 / leaf O-1-2', 'PDF p. 34 / leaf S 3'], researchNoteAnchor: 'research/curta-source-map.md#23-type-ii-service-manual',
    supports: [{ en: 'Type II service responsibility at inspected leaves: mainshaft zero position during retaining-bush work, carriage/locking-pin handling, reversing-lever assembly, clearing plate, crank and zero-positioner groups', zh: '在已检查页确认 Type II 维修责任：固定套操作时主轴须在零位、滑架/锁销处理、换向杆总成、清零板、曲柄及零位机构分组' }],
    notEstablished: [{ en: 'one dated frozen revision, Type II capacity, equality with reused Model I pictures, operator timing, complete linkage geometry, or repository control-event identity', zh: '单一带日期的冻结修订、Type II 容量、与复用 Model I 图片完全相同、操作者时序、完整连杆几何或与本站控制事件等同' }],
  },
  {
    id: 'ae-menabrea-lovelace-1843', track: 'analytical-engine', generation: { en: 'Scientific Memoirs vol. III publication, 1843', zh: '《Scientific Memoirs》第三卷出版物，1843' }, sourceTitle: 'Sketch of the Analytical Engine invented by Charles Babbage, Esq.', institution: 'Richard and John E. Taylor (original publisher)', accessHost: 'Project Gutenberg text preserving printed pages + Wikisource scan images', sourceUrl: 'https://en.wikisource.org/wiki/Scientific_Memoirs/3/Sketch_of_the_Analytical_Engine_invented_by_Charles_Babbage%2C_Esq.', recordIdentifier: 'Scientific Memoirs III, article XXIX; printed pp. 666–731; PG #75107', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct primary facsimile', inspectedDate: '2026-09-01', documentRole: 'historical publication', fullFacsimileInspected: true, pageFigureAnchors: ['printed p. 677: Mill/Store transfer', 'printed p. 679: operation/variable-card table', 'printed p. 704: operation versus variable/distributive roles'], researchNoteAnchor: 'research/analytical-engine-information-flow.md#1-menabrealovelace-1843-direct-facsimile-page-anchors',
    supports: [{ en: 'inspected printed pages distinguish Mill work from stored/variable columns and distinguish operation-card state from variable-card supply/result-location roles', zh: '已检查的印刷页区分 Mill 运算与存储/变量列，并区分操作卡状态与变量卡供数/结果定位角色' }],
    notEstablished: [{ en: 'one frozen final design, exact card holes/readers/synchronization, a complete built Engine, or the repository (ab+c)d event timing', zh: '唯一冻结的最终设计、确切卡孔/读卡器/同步、完整建成的机器，或本站 (ab+c)d 事件时序' }],
  },
  {
    id: 'ae-hpb-1888-transcription', track: 'analytical-engine', generation: { en: '1888 Bath paper / 1889 Spon compilation / modern access layers', zh: '1888 Bath 论文 / 1889 Spon 汇编 / 现代访问层' }, sourceTitle: 'Proceedings of the British Association, 1888 / The Analytical Engine', institution: 'E. & F. N. Spon 1889 publication; Cambridge University Press reproduction metadata', accessHost: 'Cambridge Core chapter metadata/preview + Fourmilab specialist transcription', sourceUrl: 'https://www.cambridge.org/core/books/abs/babbages-calculating-engines/proceedings-of-the-british-association-1888/4F94AD873CF05781394F2D9B91C1DAFB', recordIdentifier: 'chapter 32; 1889 printed compilation pp. 331–338; DOI 10.1017/CBO9780511694721.033; items 10–20 content remains transcription-only', claimType: 'H', evidenceStrength: 'E3', accessKind: 'specialist transcription', inspectedDate: '2026-09-01', documentRole: 'historical publication', fullFacsimileInspected: false, pageFigureAnchors: ['Cambridge chapter-range metadata: pp. 331–338; no content-page assignment for items 10–20'], researchNoteAnchor: 'research/analytical-engine-information-flow.md#2-h-p-babbage-paper-1888-event-1889-print-modern-access-layers',
    supports: [{ en: 'Cambridge E1 metadata identifies the 1889 compilation, chapter 32 and pp. 331–338; Fourmilab E3 transcribes Number/Directive/Operation roles and (ab+c)d in items 10–20', zh: 'Cambridge E1 元数据确认 1889 汇编、第 32 章及 331–338 页；Fourmilab E3 转录编号 10–20 的 Number/Directive/Operation 角色与 (ab+c)d' }],
    notEstablished: [{ en: 'which exact page within 331–338 contains items 10–20, facsimile typography, exact roller synchronization, a cross-walk to modern BAB drawing codes, or that the repository fixture values/order are historical', zh: '331–338 中编号 10–20 所在确切页、影印版式、滚筒精确同步、与现代 BAB 图纸代码的对照，或本站示例数值/顺序属于历史事实' }],
  },
  {
    id: 'ae-bab-a-125', track: 'analytical-engine', generation: { en: 'Analytical Engine design sheet, December 1843', zh: '分析机设计图纸，1843 年 12 月' }, sourceTitle: 'Plan of consecutive mill counting apparatus for General Plan 28', institution: 'Science Museum Group', sourceUrl: 'https://collection.sciencemuseumgroup.org.uk/documents/aa110000267/plan-of-consecutive-mill-counting-apparatus-for-general-plan-28-plan-note', recordIdentifier: 'BAB/A/125 / aa110000267; one sheet, 65×94 cm', claimType: 'H', evidenceStrength: 'E1', accessKind: 'direct archive record', inspectedDate: '2026-09-01', documentRole: 'archive drawing', researchNoteAnchor: 'research/analytical-engine-information-flow.md#3-science-museum-drawing-records',
    supports: [{ en: 'record identity, December 1843 date, extent/dimensions, and catalogued consecutive Mill counting-apparatus subject', zh: '记录身份、1843 年 12 月日期、张数/尺寸及目录所述连续 Mill 计数机构主题' }],
    notEstablished: [{ en: 'a complete built Analytical Engine, exact Store–Mill linkage, card-reader timing, or repository event sequence', zh: '完整建成的分析机、确切 Store–Mill 连杆、读卡时序或本站事件顺序' }],
  },
  {
    id: 'ae-walker-fourmilab', track: 'analytical-engine', generation: { en: 'modern executable interpretation', zh: '现代可执行解释' }, sourceTitle: 'Analytical Engine Emulator authenticity and programming-card documentation', institution: 'Fourmilab / John Walker', sourceUrl: 'https://www.fourmilab.ch/babbage/authentic.html', recordIdentifier: 'authentic.html + cards.html; inspected 2026-09-01', claimType: 'R', evidenceStrength: 'E2', accessKind: 'reconstruction documentation', inspectedDate: '2026-09-01', documentRole: 'emulator documentation', researchNoteAnchor: 'research/analytical-engine-information-flow.md#4-walkerfourmilab-reconstruction-boundary',
    supports: [{ en: 'the emulator author documents choosing one executable interpretation and merging historically separate card streams into one textual stream', zh: '模拟器作者说明其选择一种可执行解释，并把历史上分离的卡流合并为单一文本流' }],
    notEstablished: [{ en: 'nineteenth-century punched-card syntax, exact historical reader order, a built machine, or identity with this repository P/M reducer', zh: '十九世纪打孔卡语法、确切历史读卡顺序、建成机器，或与本站 P/M reducer 等同' }],
  },
] as const;

export function sourceAnchorsForTrack(track: SourceAtlasTrack): readonly NamedMachineSourceAnchor[] {
  return NAMED_MACHINE_SOURCE_ANCHORS.filter(anchor => anchor.track === track);
}

export function getNamedMachineSourceAnchor(id: string): NamedMachineSourceAnchor {
  const anchor = NAMED_MACHINE_SOURCE_ANCHORS.find(item => item.id === id);
  if (!anchor) throw new Error(`unknown named-machine source anchor: ${id}`);
  return anchor;
}
