export interface BilingualCarryText { en: string; zh: string; }
export type CarryClaimType = 'H' | 'R';
export type CarryEvidenceStrength = 'E1' | 'E2' | 'E3' | 'E4';
export interface CarryEvidenceProfile {
  id: 'pascal-avis' | 'pascaline-cnam' | 'pascaline-cmu-reconstruction' | 'felt-us366945' | 'felt-us762520' | 'comptometer-model-a';
  family: BilingualCarryText;
  dateOrModel: string;
  claimType: CarryClaimType;
  evidenceStrength: CarryEvidenceStrength;
  sourceLabel: string;
  sourceUrl: string;
  documentedRoles: readonly BilingualCarryText[];
  operatorImplication: BilingualCarryText;
  notEstablished: readonly BilingualCarryText[];
}
export const CARRY_EVIDENCE_PROFILES: readonly CarryEvidenceProfile[] = [
  { id: 'pascal-avis', family: { en: "Pascal's operational claim", zh: '帕斯卡本人的操作主张' }, dateOrModel: 'Avis nécessaire, 1645 public notice; 1923 edited text', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Blaise Pascal, Avis nécessaire (edited public text)', sourceUrl: 'https://fr.wikisource.org/wiki/%C5%92uvres_de_Blaise_Pascal/Lettre_D%C3%A9dicatoire_de_la_Machine_Arithm%C3%A9tique_et_Avis_n%C3%A9cessaire/Avis', documentedRoles: [{ en: 'the machine performs carrying and borrowing without the operator retaining those values mentally', zh: '机器自行完成进位与借位，操作者无需在头脑中记忆这些数' }, { en: 'mechanical complexity is defended as necessary for simple, convenient, durable operation', zh: '帕斯卡认为，为获得简单、方便且耐用的操作，机构复杂性是必要的' }], operatorImplication: { en: 'operator supplies the intended arithmetic movement; the machine relieves memory work', zh: '操作者给出算术动作，机器承担记忆进位/借位的工作' }, notEstablished: [{ en: "the Avis does not describe sautoir geometry", zh: '《Avis》没有描述 sautoir 的几何结构' }] },
  { id: 'pascaline-cnam', family: { en: 'Preserved Pascal arithmetic machine', zh: '留存的帕斯卡算术机' }, dateOrModel: 'Cnam inventory 19600-0000; object dated 1652', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Musée des Arts et Métiers/Cnam, Machine arithmétique de Pascal', sourceUrl: 'https://www.arts-et-metiers.net/musee/machine-arithmetique-de-pascal-chiffres-plus-sous-et-deniers-0', documentedRoles: [{ en: 'institutional description attributes automatic carry to the small sautoir component', zh: '机构说明把自动进位归于名为 sautoir 的小部件' }], operatorImplication: { en: 'dial operation can cross a denomination boundary without mental carry', zh: '拨轮操作越过数位边界时不需要操作者心算进位' }, notEstablished: [{ en: 'one universal geometry across the small set of surviving machines', zh: '少量留存机器之间具有统一几何结构' }] },
  { id: 'pascaline-cmu-reconstruction', family: { en: 'Modern Pascaline reconstruction', zh: '现代 Pascaline 复原' }, dateOrModel: 'CMU physical reconstruction', claimType: 'R', evidenceStrength: 'E2', sourceLabel: 'Carnegie Mellon University, Pascaline reconstruction assembly', sourceUrl: 'https://www.cs.cmu.edu/~dst/Pascaline/assembly-instructions.html', documentedRoles: [{ en: 'a documented reconstruction implements spring-loaded carry pawls and sautoir/carry-lever assemblies', zh: '有文档的复原采用弹簧加载的进位棘爪和 sautoir/进位杆组件' }], operatorImplication: { en: 'the reconstruction demonstrates one plausible automatic boundary transfer', zh: '该复原展示了一种可行的自动跨位传递解释' }, notEstablished: [{ en: 'identity with every seventeenth-century manufactured detail', zh: '与十七世纪所有制造细节完全相同' }] },
  { id: 'felt-us366945', family: { en: 'Early Felt key-driven carry', zh: 'Felt 早期按键驱动进位' }, dateOrModel: 'US 366,945 (1887)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Dorr E. Felt, US366945A, Adding Machine', sourceUrl: 'https://patents.google.com/patent/US366945A/en', documentedRoles: [{ en: 'value keys directly actuate denominational indicator wheels', zh: '数值键直接驱动各数位的指示轮' }, { en: 'wheel cams charge spring levers; carry pawls advance the next order automatically', zh: '轮上凸轮为弹簧杆蓄力，进位棘爪自动推进更高一位' }], operatorImplication: { en: 'the key supplies the local addition while stored spring work handles carry independently of key pressure', zh: '按键提供本位加法，弹簧所储能量独立承担进位，操作者无需额外加力' }, notEstablished: [{ en: 'later Duplex simultaneous-column scheduling', zh: '后来 Duplex 的多列同时操作调度' }, { en: 'all Comptometer production revisions', zh: '所有 Comptometer 量产修订版' }] },
  { id: 'felt-us762520', family: { en: 'Felt delayed-carry Duplex design', zh: 'Felt 延迟进位 Duplex 设计' }, dateOrModel: 'US 762,520 (1904)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Dorr E. Felt, US762520A, Calculating Machine', sourceUrl: 'https://patents.google.com/patent/US762520A/en', documentedRoles: [{ en: 'the patent identifies lost carry when simultaneous higher-column key motion overlaps carry', zh: '专利指出：更高位按键动作与进位重叠时，进位可能丢失' }, { en: 'carrying gear 41 and spring 43 store work; latch 53 delays carry until the receiving column actuator returns', zh: '进位齿轮 41 与弹簧 43 储能；闩锁 53 延迟进位，直至接收位的列驱动器复位' }], operatorImplication: { en: 'different denominations may be struck together because carry is scheduled around the receiving key stroke', zh: '由于进位会绕开接收位按键行程进行调度，操作者可以同时按下不同数位的键' }, notEstablished: [{ en: 'exact linkage in every manufactured Model A or later machine', zh: '每台量产 Model A 或后续机器都采用完全相同的连杆结构' }, { en: 'the repository serialized event order as patent timing', zh: '把本仓串行事件顺序视为专利时序' }] },
  { id: 'comptometer-model-a', family: { en: 'Comptometer Model A production context', zh: 'Comptometer Model A 量产背景' }, dateOrModel: 'Smithsonian/NMAH nmah_690484', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Smithsonian/NMAH, Comptometer Model A, nmah_690484', sourceUrl: 'https://www.si.edu/object/comptometer-model%3Anmah_690484', documentedRoles: [{ en: 'catalog identifies the Model A as the first duplex machine and says each column could add, receive, and carry simultaneously', zh: '目录将 Model A 识别为首款 duplex 机器，并称每列可同时加数、接收与进位' }], operatorImplication: { en: 'multi-column entry became a documented production-level operating capability', zh: '多列输入成为有目录记录的量产级操作能力' }, notEstablished: [{ en: 'the exact US762520 linkage or timing in the catalogued object', zh: '目录对象中 US762520 的确切连杆或时序' }] },
] as const;
export function getCarryEvidenceProfile(id: CarryEvidenceProfile['id']): CarryEvidenceProfile {
  const profile = CARRY_EVIDENCE_PROFILES.find(item => item.id === id); if (!profile) throw new Error(`unknown carry evidence profile: ${id}`); return profile;
}
