export interface BilingualCarryText { en: string; zh: string; }
export type CarryClaimType = 'H' | 'R';
export type CarryEvidenceStrength = 'E1' | 'E2' | 'E3' | 'E4';
export interface CarryEvidenceProfile {
  id: 'pascal-avis' | 'pascaline-cnam' | 'pascaline-cmu-reconstruction' | 'felt-us366945' | 'felt-us762520' | 'comptometer-model-a' | 'odhner-us514725' | 'odhner-us1377269' | 'talamini-marchant-us1867603' | 'thomas-1820-patent' | 'thomas-1820-smithsonian' | 'thomas-1865' | 'thomas-de-bojano-1880' | 'thomas-1880-revision-history';
  family: BilingualCarryText;
  dateOrModel: string;
  claimType: CarryClaimType;
  evidenceStrength: CarryEvidenceStrength;
  sourceLabel: string;
  sourceUrl: string;
  documentedRoles: readonly BilingualCarryText[];
  operatorImplication: BilingualCarryText;
  notEstablished: readonly BilingualCarryText[];
}
export const CARRY_EVIDENCE_PROFILES: readonly CarryEvidenceProfile[] = [
  { id: 'pascal-avis', family: { en: "Pascal's operational claim", zh: '帕斯卡本人的操作主张' }, dateOrModel: 'Avis nécessaire, 1645 public notice; 1923 edited text', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Blaise Pascal, Avis nécessaire (edited public text)', sourceUrl: 'https://fr.wikisource.org/wiki/%C5%92uvres_de_Blaise_Pascal/Lettre_D%C3%A9dicatoire_de_la_Machine_Arithm%C3%A9tique_et_Avis_n%C3%A9cessaire/Avis', documentedRoles: [{ en: 'the machine performs carrying and borrowing without the operator retaining those values mentally', zh: '机器自行完成进位与借位，操作者无需在头脑中记忆这些数' }, { en: 'mechanical complexity is defended as necessary for simple, convenient, durable operation', zh: '帕斯卡认为，为获得简单、方便且耐用的操作，机构复杂性是必要的' }], operatorImplication: { en: 'operator supplies the intended arithmetic movement; the machine relieves memory work', zh: '操作者给出算术动作，机器承担记忆进位/借位的工作' }, notEstablished: [{ en: "the Avis does not describe sautoir geometry", zh: '《Avis》没有描述 sautoir 的几何结构' }] },
  { id: 'pascaline-cnam', family: { en: 'Preserved Pascal arithmetic machine', zh: '留存的帕斯卡算术机' }, dateOrModel: 'Cnam inventory 19600-0000; object dated 1652', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Musée des Arts et Métiers/Cnam, Machine arithmétique de Pascal', sourceUrl: 'https://www.arts-et-metiers.net/musee/machine-arithmetique-de-pascal-chiffres-plus-sous-et-deniers-0', documentedRoles: [{ en: 'institutional description attributes automatic carry to the small sautoir component', zh: '机构说明把自动进位归于名为 sautoir 的小部件' }], operatorImplication: { en: 'dial operation can cross a denomination boundary without mental carry', zh: '拨轮操作越过数位边界时不需要操作者心算进位' }, notEstablished: [{ en: 'one universal geometry across the small set of surviving machines', zh: '少量留存机器之间具有统一几何结构' }] },
  { id: 'pascaline-cmu-reconstruction', family: { en: 'Modern Pascaline reconstruction', zh: '现代 Pascaline 复原' }, dateOrModel: 'CMU physical reconstruction', claimType: 'R', evidenceStrength: 'E2', sourceLabel: 'Carnegie Mellon University, Pascaline reconstruction assembly', sourceUrl: 'https://www.cs.cmu.edu/~dst/Pascaline/assembly-instructions.html', documentedRoles: [{ en: 'a documented reconstruction implements spring-loaded carry pawls and sautoir/carry-lever assemblies', zh: '有文档的复原采用弹簧加载的进位棘爪和 sautoir/进位杆组件' }], operatorImplication: { en: 'the reconstruction demonstrates one plausible automatic boundary transfer', zh: '该复原展示了一种可行的自动跨位传递解释' }, notEstablished: [{ en: 'identity with every seventeenth-century manufactured detail', zh: '与十七世纪所有制造细节完全相同' }] },
  { id: 'felt-us366945', family: { en: 'Early Felt key-driven carry', zh: 'Felt 早期按键驱动进位' }, dateOrModel: 'US 366,945 (1887)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Dorr E. Felt, US366945A, Adding Machine', sourceUrl: 'https://patents.google.com/patent/US366945A/en', documentedRoles: [{ en: 'value keys directly actuate denominational indicator wheels', zh: '数值键直接驱动各数位的指示轮' }, { en: 'wheel cams charge spring levers; carry pawls advance the next order automatically', zh: '轮上凸轮为弹簧杆蓄力，进位棘爪自动推进更高一位' }], operatorImplication: { en: 'the key supplies the local addition while stored spring work handles carry independently of key pressure', zh: '按键提供本位加法，弹簧所储能量独立承担进位，操作者无需额外加力' }, notEstablished: [{ en: 'later Duplex simultaneous-column scheduling', zh: '后来 Duplex 的多列同时操作调度' }, { en: 'all Comptometer production revisions', zh: '所有 Comptometer 量产修订版' }] },
  { id: 'felt-us762520', family: { en: 'Felt delayed-carry Duplex design', zh: 'Felt 延迟进位 Duplex 设计' }, dateOrModel: 'US 762,520 (1904)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Dorr E. Felt, US762520A, Calculating Machine', sourceUrl: 'https://patents.google.com/patent/US762520A/en', documentedRoles: [{ en: 'the patent identifies lost carry when simultaneous higher-column key motion overlaps carry', zh: '专利指出：更高位按键动作与进位重叠时，进位可能丢失' }, { en: 'carrying gear 41 and spring 43 store work; latch 53 delays carry until the receiving column actuator returns', zh: '进位齿轮 41 与弹簧 43 储能；闩锁 53 延迟进位，直至接收位的列驱动器复位' }], operatorImplication: { en: 'different denominations may be struck together because carry is scheduled around the receiving key stroke', zh: '由于进位会绕开接收位按键行程进行调度，操作者可以同时按下不同数位的键' }, notEstablished: [{ en: 'exact linkage in every manufactured Model A or later machine', zh: '每台量产 Model A 或后续机器都采用完全相同的连杆结构' }, { en: 'the repository serialized event order as patent timing', zh: '把本仓串行事件顺序视为专利时序' }] },
  { id: 'comptometer-model-a', family: { en: 'Comptometer Model A production context', zh: 'Comptometer Model A 量产背景' }, dateOrModel: 'Smithsonian/NMAH nmah_690484', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Smithsonian/NMAH, Comptometer Model A, nmah_690484', sourceUrl: 'https://www.si.edu/object/comptometer-model%3Anmah_690484', documentedRoles: [{ en: 'catalog identifies the Model A as the first duplex machine and says each column could add, receive, and carry simultaneously', zh: '目录将 Model A 识别为首款 duplex 机器，并称每列可同时加数、接收与进位' }], operatorImplication: { en: 'multi-column entry became a documented production-level operating capability', zh: '多列输入成为有目录记录的量产级操作能力' }, notEstablished: [{ en: 'the exact US762520 linkage or timing in the catalogued object', zh: '目录对象中 US762520 的确切连杆或时序' }] },
  { id: 'odhner-us514725', family: { en: 'Odhner baseline rotary transfer', zh: 'Odhner 基线旋转进位' }, dateOrModel: 'US 514,725 (1894)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'W. T. Odhner, US514725A, Calculating Apparatus', sourceUrl: 'https://patents.google.com/patent/US514725A/en', documentedRoles: [{ en: 'register crossing positions a transfer arm; a normally displaced carry pin is deflected to advance the next order by one tooth', zh: '寄存轮越界使传递臂就位；通常偏置的进位销被拨入有效位置，使更高一位前进一步' }, { en: 'intermediate wheels are described as ensuring exact register movement and limiting overtravel during rapid rotation', zh: '专利称中间轮可保证寄存轮准确运动，并防止快速旋转时过冲' }], operatorImplication: { en: 'crank rotation transfers selected pins and an eligible decimal crossing can condition the next order', zh: '曲柄旋转传递已选销，满足条件的十进制越界可使更高一位进入可进位状态' }, notEstablished: [{ en: 'identical geometry in every later Original-Odhner production revision', zh: '所有后续 Original-Odhner 量产修订版都具有相同几何结构' }, { en: 'quantitative speed, force, wear, or tolerance limits', zh: '定量速度、力、磨损或公差极限' }] },
  { id: 'odhner-us1377269', family: { en: 'Valentin Odhner rapid-rotation transfer improvement', zh: 'Valentin Odhner 快速旋转传递改进' }, dateOrModel: 'US 1,377,269 (1921)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Valentin Jakob Odhner, US1377269A, Transfer Mechanism', sourceUrl: 'https://patents.google.com/patent/US1377269A/en', documentedRoles: [{ en: 'the patent says rapid rotation can throw the adjusted transfer arm back so carry pins do not act and miscalculation occurs', zh: '专利称快速旋转可能把已就位的传递臂撞回，使进位销不动作并导致误算' }, { en: 'a revised fulcrum minimizes the destabilizing turning moment; conical contact increases contact area and reduces wear', zh: '改进支点使使传递臂脱位的转矩最小化；锥面接触增大接触范围并减少磨损' }], operatorImplication: { en: 'correct arithmetic depends on the transfer element remaining conditioned while the rotary opportunity passes', zh: '正确算术依赖传递元件在旋转进位机会经过时保持就位' }, notEstablished: [{ en: 'a safe RPM, probability-of-failure curve, field failure rate, or universal production adoption', zh: '安全转速、失效概率曲线、现场故障率或所有量产机采用情况' }] },
  { id: 'talamini-marchant-us1867603', family: { en: 'Talamini/Marchant successive carry scheduling', zh: 'Talamini/Marchant 连续进位调度' }, dateOrModel: 'US 1,867,603 (1932)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Louis Talamini / Marchant, US1867603A, Calculating Machine', sourceUrl: 'https://patents.google.com/patent/US1867603A/en', documentedRoles: [{ en: 'dependent carry teeth cannot operate simultaneously; superior-order opportunities must be staggered so a carry-created crossing can condition the next order', zh: '相互依赖的进位齿不能同时动作；更高位机会必须错开，让前一次进位造成的越界先使下一位就绪' }, { en: 'the described phase-overlap surfaces reduce safe peripheral displacement by about 22 percent in the patent experiment', zh: '专利所述阶段重叠表面在该实验中把安全圆周间距降低约 22%' }], operatorImplication: { en: 'rotary capacity and attainable speed are constrained by how successive conditioning and driving opportunities are spaced', zh: '旋转机构的容量与可达速度受连续就位/驱动机会间距约束' }, notEstablished: [{ en: 'authorship by Odhner, universal Odhner geometry, or a universal 22 percent performance gain', zh: '该改进由 Odhner 发明、所有 Odhner 结构相同，或普遍存在 22% 性能增益' }, { en: 'historical angles/times represented by repository ordinal slots', zh: '本仓序数槽表示历史角度或时间' }] },
  { id: 'thomas-1820-patent', family: { en: 'Thomas early carry patent', zh: 'Thomas 早期进位专利' }, dateOrModel: 'French Brevet 1420 (1820)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Charles-Xavier Thomas de Colmar, Brevet No. 1420', sourceUrl: 'https://arithmometre.org/Brevets/PageBrevet1820FR.html', documentedRoles: [{ en: 'the patent separates multiplier, multiplicand, and carry systems and describes a patent-specific spring/fork/wheel transfer', zh: '专利把乘数、被乘数和进位列为三个独立运动系统，并描述该专利特有的弹簧、叉件与轮系传递' }], operatorImplication: { en: 'the early design already treats carry as a separate conditioned movement system', zh: '这一早期设计已经把进位视为独立的条件化运动系统' }, notEstablished: [{ en: 'geometry of the later stabilized commercial Thomas machines', zh: '后来稳定商用 Thomas 机器的几何结构' }] },
  { id: 'thomas-1820-smithsonian', family: { en: 'Oldest surviving Thomas object boundary', zh: '最早留存 Thomas 实物边界' }, dateOrModel: 'Smithsonian nmah_690692, ca. 1820', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Smithsonian/NMAH, oldest surviving Thomas Arithmometer', sourceUrl: 'https://americanhistory.si.edu/collections/object/nmah_690692', documentedRoles: [{ en: 'the catalog says the surviving object is not identical to the 1820 patent drawings and more closely resembles 1821 drawings for the Hoyau report', zh: '目录称该留存实物与 1820 年专利图并不相同，更接近为 Hoyau 报告于 1821 年绘制的图样' }], operatorImplication: { en: 'patent date, surviving object, and later commercial revision must remain separate contexts', zh: '专利年代、留存实物与后续商用修订版必须保持为不同语境' }, notEstablished: [{ en: 'the exact design transition from the 1820 patent to the surviving object', zh: '从 1820 年专利到该留存实物的确切设计演变' }] },
  { id: 'thomas-1865', family: { en: 'Thomas stepped-drum carry revision', zh: 'Thomas 阶梯鼓进位修订' }, dateOrModel: 'French Brevet 68923 (1865)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Charles-Xavier Thomas de Colmar, Brevet No. 68923', sourceUrl: 'https://arithmometre.org/Brevets/PageBrevet1865FR.html', documentedRoles: [{ en: 'successively phased stepped cylinders make carries fall one after another to avoid errors', zh: '依次错相的阶梯鼓使进位一个接一个落下，以避免错误' }, { en: 'the patent says rapid motion could overrun a dial by one or two teeth and describes a moderation-cylinder/Malta-cross stop', zh: '专利称快速运动可能使表盘多走一到两齿，并描述调速圆柱与马耳他十字止动关系' }, { en: 'older simultaneous vertical carry loads could lift the dial plate, weaken engagement, and give false results; the replacement conditions carry horizontally', zh: '旧式多个垂直进位负载同时作用时可能顶起表盘板、削弱啮合并产生错误结果；替代方案改为水平触发进位' }], operatorImplication: { en: 'one crank cycle needs ordered carry action and reliable full conditioning, not a simultaneous arithmetic side effect', zh: '一次曲柄循环需要有序进位和可靠的完全就位，而不是同时发生的算术副作用' }, notEstablished: [{ en: 'exact tooth angles/times, safe crank rate, loads, failure frequency, or identical geometry in every production revision', zh: '确切齿角/时间、安全摇速、载荷、故障频率，或所有量产修订版采用相同几何结构' }] },
  { id: 'thomas-de-bojano-1880', family: { en: 'Thomas de Bojano carry simplification proposal', zh: 'Thomas de Bojano 进位简化提案' }, dateOrModel: 'French Brevet 138912 (1880)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'Thomas de Bojano, Brevet No. 138912', sourceUrl: 'https://arithmometre.org/Brevets/PageBrevet1880FR.html', documentedRoles: [{ en: 'the patent recaps a 20-part carry effect and proposes a 10-part arrangement', zh: '专利回顾每套 20 个零件的进位机构，并提出 10 个零件的新方案' }, { en: 'carries conditioned during a crank turn remain down until a crank-home reset action', zh: '曲柄一周内已触发的进位保持落下，直到曲柄归位时统一复位' }], operatorImplication: { en: 'the proposal reduces the enumerated mechanism count while retaining a crank-cycle reset responsibility', zh: '该提案减少列举的机构零件数，同时保留曲柄循环归位复位的责任' }, notEstablished: [{ en: 'production adoption of the proposed 20-to-10-part simplification', zh: '所提 20→10 零件简化方案得到量产采用' }] },
  { id: 'thomas-1880-revision-history', family: { en: 'Specialist 1880 production interpretation', zh: '1880 年量产情况的专业解释' }, dateOrModel: 'Arithmometre.org revision chronology', claimType: 'R', evidenceStrength: 'E3', sourceLabel: 'Arithmometre.org, chronology and revision history', sourceUrl: 'https://arithmometre.org/Biographie/ChronologieENG.html', documentedRoles: [{ en: 'the specialist chronology calls the 1880 patent effectively a phantom and reports no referenced machine with its simplified carry', zh: '专业年表称 1880 年专利实际上近似“幽灵专利”，并称已收录机器中未见其简化进位机构' }, { en: 'it interprets nearly all known French and foreign Arithmometers into the 1920s as retaining the T1865 pattern', zh: '该年表判断，已知法国及外国 Arithmometer 到 1920 年代大多仍沿用 T1865 模式' }], operatorImplication: { en: 'production history must be evaluated separately from a patent proposal', zh: '量产历史必须与专利提案分开判断' }, notEstablished: [{ en: 'an exhaustive artifact census or proof that no unrecorded implementation existed', zh: '穷尽全部实物的普查，或证明不存在未记录的实现' }] },
] as const;
export function getCarryEvidenceProfile(id: CarryEvidenceProfile['id']): CarryEvidenceProfile {
  const profile = CARRY_EVIDENCE_PROFILES.find(item => item.id === id); if (!profile) throw new Error(`unknown carry evidence profile: ${id}`); return profile;
}
