export interface BilingualOutputText { en: string; zh: string; }
export type OutputClaimType = 'H' | 'R' | 'H/R';
export type OutputEvidenceStrength = 'E1' | 'E2' | 'E3' | 'E4';
export interface OutputContractProfile {
  id: 'burroughs-calculator-register' | 'burroughs-class-3' | 'burroughs-style-9' | 'swalm-us885202' | 'difference-engine-output';
  family: BilingualOutputText; dateOrModel: string; claimType: OutputClaimType; evidenceStrength: OutputEvidenceStrength;
  sourceLabel: string; sourceUrl: string; outputMedium: BilingualOutputText;
  documentedBehaviors: readonly BilingualOutputText[]; notEstablished: readonly BilingualOutputText[];
}
export const OUTPUT_CONTRACT_PROFILES: readonly OutputContractProfile[] = [
  { id: 'burroughs-calculator-register', family: { en: 'Non-printing Burroughs Calculator', zh: '非打印 Burroughs Calculator' }, dateOrModel: 'identified NMAH object nmah_690197', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Smithsonian/NMAH, Burroughs Calculator, nmah_690197', sourceUrl: 'https://americanhistory.si.edu/collections/object/nmah_690197', outputMedium: { en: 'result wheels/windows; no machine-produced paper listing documented', zh: '结果轮/窗口；未记录机器自动生成纸面清单' }, documentedBehaviors: [{ en: 'identified as a full-keyboard key-driven non-printing adding machine', zh: '该对象被识别为全键盘、按键驱动的非打印加法机' }], notEstablished: [{ en: 'office copying procedure, clearing sequence, or all Burroughs Calculator revisions', zh: '办公抄录流程、清零顺序或全部 Burroughs Calculator 修订版' }] },
  { id: 'burroughs-class-3', family: { en: 'Burroughs Class 3 Adding Machine', zh: 'Burroughs Class 3 加法机' }, dateOrModel: 'identified NMAH object nmah_690654', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Smithsonian/NMAH, Burroughs Class 3, nmah_690654', sourceUrl: 'https://americanhistory.si.edu/collections/object/nmah_690654', outputMedium: { en: 'operator-visible paper tape on the identified object', zh: '该对象使用操作者可见的纸带' }, documentedBehaviors: [{ en: 'catalog documents printing/paper tape and non-add, total, subtotal, and repeat controls', zh: '目录记录打印/纸带及不累加、总计、小计和重复控制' }], notEstablished: [{ en: 'universal Burroughs paper path, control linkage, or timing', zh: '通用于 Burroughs 的纸路、控制连杆或时序' }] },
  { id: 'burroughs-style-9', family: { en: 'Burroughs Style 9 Adding Machine', zh: 'Burroughs Style 9 加法机' }, dateOrModel: 'identified NMAH object nmah_690660', claimType: 'H', evidenceStrength: 'E2', sourceLabel: 'Smithsonian/NMAH, Burroughs Style 9, nmah_690660', sourceUrl: 'https://americanhistory.si.edu/collections/object/nmah_690660', outputMedium: { en: 'wide-carriage printing on tape or sheets; printing not operator-visible in the documented arrangement', zh: '宽位架在纸带或纸张上打印；记录的布置中操作者看不到打印' }, documentedBehaviors: [{ en: 'identified output arrangement differs from the Class 3 visible-tape example', zh: '该输出布置不同于 Class 3 的可见纸带实例' }], notEstablished: [{ en: 'shared paper-feed/type-bar geometry with Class 3 or other styles', zh: '与 Class 3 或其他款式共享的走纸/字杆几何' }] },
  { id: 'swalm-us885202', family: { en: 'Adding/listing total and subtotal design', zh: '加法/列单机总计与小计设计' }, dateOrModel: 'William E. Swalm, US 885,202 (1908)', claimType: 'H', evidenceStrength: 'E1', sourceLabel: 'William E. Swalm, US885202A, Adding and Listing Machine', sourceUrl: 'https://patents.google.com/patent/US885202A/en', outputMedium: { en: 'printed individual items and totals/subtotals', zh: '打印逐项记录及总计/小计' }, documentedBehaviors: [{ en: 'total prints a footing and leaves accumulating wheels at zero in the described class', zh: '在所述机器类别中，总计打印合计并使累加轮留在零位' }, { en: 'subtotal prints the current footing while retaining accumulation for later items', zh: '小计打印当前合计，同时保留累加值以继续录入' }], notEstablished: [{ en: 'behavior or mechanism of every Burroughs production revision', zh: '全部 Burroughs 量产修订版的行为或机构' }, { en: 'the repository ledger event order as historical timing', zh: '把本仓台账事件顺序视为历史时序' }] },
  { id: 'difference-engine-output', family: { en: 'Difference Engine persistent-output lineage', zh: '差分机持久输出脉络' }, dateOrModel: 'Babbage designs; 1991/2002 reconstruction; built Scheutz comparison', claimType: 'H/R', evidenceStrength: 'E2', sourceLabel: 'Repository source map: Difference Engine provenance and tabular-output boundary', sourceUrl: 'https://github.com/tmzncty/mechanical-computing-playground/blob/main/research/difference-engine-source-map.md', outputMedium: { en: 'check-copy/table print and stereotype/master roles at source-supported levels', zh: '在资料支持范围内的检查副本/表格打印及铸版/母版角色' }, documentedBehaviors: [{ en: 'addresses transcription and re-copying in mathematical table production, unlike office transaction listing', zh: '面向数学表格生产中的转录/重抄问题，不同于办公交易列单' }], notEstablished: [{ en: 'historical printer timing/geometry or identity with office adding-machine technology', zh: '历史打印时序/几何，或与办公加法机技术相同' }, { en: 'the repository check-copy events as historical phases', zh: '把本仓检查副本事件视为历史阶段' }] },
] as const;
export function getOutputContractProfile(id: OutputContractProfile['id']): OutputContractProfile {
  const profile = OUTPUT_CONTRACT_PROFILES.find(item => item.id === id); if (!profile) throw new Error(`unknown output-contract profile: ${id}`); return profile;
}
