import { createCrankTrace, digitsToString, createDecimalRegister, reduceDecimalRegisterEvent } from './mechanism-core';
import { squarePreset, cubicPreset, transitionDifference, type DifferenceState } from './mechanisms/difference-column';
import { compare314x27 } from './exhibits/multiplication-compare';
import { sampleFlow } from './exhibits/analytical-engine-flow';
import { createIntegrator, integrate, type IntegratorState } from './mechanisms/continuous-integrator';
import { cycle, evaluate, type StageAState } from './backprop/core/stage-a';
import { createPhaseMachine, runPhaseCycle, stepPhase, STAGE_A_PHASES, type PhaseMachineState } from './backprop/core/phase-machine';
import { mapStageA } from './backprop/mechanical-mapping';
import './style.css';

const root = document.querySelector('main')!;
let carryTrace = createCrankTrace([9, 9, 0, 0]);
let carryIndex = 0;
let diff: DifferenceState = squarePreset();
let diffPreset = 'n²';
let diffEvents: string[] = [];
let integrator: IntegratorState = createIntegrator(1, 0.1);
let back: StageAState = evaluate({ x1: 2, x2: 3, w1: 0, w2: 0, target: 10, learningRate: 0.01 });
let phaseMachine: PhaseMachineState = createPhaseMachine(back);
let backPreset = 'stable';
type Locale = 'en' | 'zh';
let locale: Locale = (localStorage.getItem('mechanical-locale') as Locale) || 'en';
const navText: Record<string, [string, string]> = { Overview: ['Overview', '总览'], 'Visible carry': ['Visible carry', '可见进位'], 'Finite differences': ['Finite differences', '有限差分'], Multiplication: ['Multiplication', '乘法机制'], 'Analytical Engine': ['Analytical Engine', '分析机'], Curta: ['Curta', 'Curta'], Continuous: ['Continuous', '连续计算'], 'Hand-crank backprop': ['Hand-crank backprop', '手摇反向传播'], About: ['About', '关于'] };
const t = (en: string, zh: string) => locale === 'zh' ? zh : en;
function applyTranslations() {
  const replacements: Array<[string, string]> = [['A deterministic laboratory: computation shown as ordered mechanical state transitions.', '确定性实验室：把计算呈现为有序的机械状态转换。'], ['Core state is the source of truth.', '核心状态是真相来源。'], ['Models marked ', '标记为 '], [' are pedagogical abstractions, not historical reconstructions.', ' 的模型是教学抽象，不是历史复原。'], ['Choose an exhibit', '选择一个展品'], ['Method', '方法'], ['Every exhibit separates numerical state, deterministic transitions, ordered events, and presentation. Replayable traces make the mechanism inspectable without relying on animation.', '每个展品都将数值状态、确定性转换、有序事件和呈现层分开。可重放轨迹让机制无需依赖动画也能被检查。'], ['Each wheel step and carry propagation is a separate event. The UI replays the trace; it does not recalculate the answer.', '每次轮齿移动和进位传播都是独立事件。界面只重放轨迹，不重新计算答案。'], ['Step event', '逐事件推进'], ['Complete crank', '完成一轮曲柄'], ['Reset', '重置'], ['Crank one row', '摇动一行'], ['Advance one time step', '前进一步'], ['Turn one phase', '转动一个阶段'], ['Complete cycle', '完成一轮'], ['Train 8 cycles', '训练 8 轮'], ['Overshoot preset', '过冲预设'], ['Reset weights', '重置权重'], ['Show math', '显示数学'], ['Update order:', '更新顺序：'], ['Repeated addition advances the leading value. Highest differences stay constant for a matching polynomial.', '重复加法推进最低阶数值；对于对应多项式，最高阶差分保持不变。'], ['Multiplication mechanisms', '乘法机制'], ['Analytical Engine information flow', '分析机信息流'], ['Continuous mechanical computing', '连续机械计算'], ['Hand-crank backpropagation', '手摇反向传播'], ['About this laboratory', '关于本实验室'], ['GRADE D · pedagogical column model', 'D 级 · 教学列模型'], ['PEDAGOGICAL TRANSLATION · NOT A HISTORICAL MACHINE', '教学转换 · 不是历史机器'], ['GRADE D · Euler teaching model', 'D 级 · Euler 教学模型']];
  if (locale === 'en') return;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes: Text[] = []; while (walker.nextNode()) nodes.push(walker.currentNode as Text);
  for (const node of nodes) for (const [en, zh] of replacements) if (node.nodeValue?.includes(en)) node.nodeValue = node.nodeValue.replaceAll(en, zh);
}

const carryState = () => carryTrace.events.slice(0, carryIndex).reduce(reduceDecimalRegisterEvent, createDecimalRegister(carryTrace.initialState.digits));
const eventText = () => carryTrace.events.slice(0, carryIndex).map((e) => `${String(e.sequence).padStart(2, '0')} · ${e.type}${e.type === 'WHEEL_STEP' ? ` wheel ${e.wheel.index}: ${e.from}→${e.to}` : ''}`).join('\n') || '—';
const esc = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;');

function shell(title: string, body: string) {
  root.innerHTML = `<header><p class="eyebrow">MECHANICAL COMPUTING PLAYGROUND</p><h1>${title}</h1><p class="lede">A deterministic laboratory: computation shown as ordered mechanical state transitions.</p><button class="language" id="language-toggle" type="button" aria-label="${t('Switch to Chinese','切换到英文')}">${t('中文','English')}</button><nav>${[['/','Overview'],['/visible-carry','Visible carry'],['/finite-difference','Finite differences'],['/multiplication','Multiplication'],['/analytical-engine','Analytical Engine'],['/curta','Curta'],['/continuous','Continuous'],['/hand-crank-backprop','Hand-crank backprop'],['/about','About']].map(([href,label]) => `<a href="#${href}">${t(...navText[label])}</a>`).join('')}</nav></header>${body}<footer>${t('Core state is the source of truth. Models marked <b>GRADE D</b> are pedagogical abstractions, not historical reconstructions.','核心状态是真相来源。标记为 <b>D 级</b> 的模型是教学抽象，不是历史复原。')}</footer>`;
    document.querySelector('#language-toggle')?.addEventListener('click', () => { locale = locale === 'en' ? 'zh' : 'en'; localStorage.setItem('mechanical-locale', locale); render(); });
}
function overview() { shell('Mechanical Computing Playground', `<section><h2>Choose an exhibit</h2><div class="cards"><a class="card" href="#/visible-carry"><b>Visible carry</b><span>0099 + 1, one event at a time</span></a><a class="card" href="#/finite-difference"><b>Finite differences</b><span>Generate polynomial tables by addition</span></a><a class="card" href="#/multiplication"><b>Multiplication</b><span>Compare three operation decompositions</span></a><a class="card" href="#/hand-crank-backprop"><b>Hand-crank backprop</b><span>Forward, error, gradient, update</span></a></div></section><section><h2>Method</h2><p>Every exhibit separates numerical state, deterministic transitions, ordered events, and presentation. Replayable traces make the mechanism inspectable without relying on animation.</p></section>`); }
function visibleCarry() { const digits = [...carryState().digits].reverse(); shell('Visible carry', `<section><h2>0099 + 1</h2><div class="wheels">${digits.map((d, i) => `<span class="wheel ${carryIndex > 0 ? 'active' : ''}" aria-label="wheel ${digits.length - i}">${d}</span>`).join('')}</div><p class="big"><b>${digitsToString(carryState().digits)}</b> · event ${carryIndex}/${carryTrace.events.length}</p><button id="carry-step">Step event</button><button id="carry-crank">Complete crank</button><button id="carry-reset">Reset</button><pre>${esc(eventText())}</pre><p>Each wheel step and carry propagation is a separate event. The UI replays the trace; it does not recalculate the answer.</p></section>`); document.querySelector('#carry-step')?.addEventListener('click', () => { carryIndex = Math.min(carryIndex + 1, carryTrace.events.length); visibleCarry(); }); document.querySelector('#carry-crank')?.addEventListener('click', () => { carryIndex = carryTrace.events.length; visibleCarry(); }); document.querySelector('#carry-reset')?.addEventListener('click', () => { carryIndex = 0; visibleCarry(); }); }
function finiteDifference() { shell('Finite differences', `<section><p class="badge">GRADE D · pedagogical column model</p><h2>${diffPreset}</h2><p>Repeated addition advances the leading value. Highest differences stay constant for a matching polynomial.</p><div class="state-grid">${diff.columns.map((c, i) => `<div><small>Δ${i}</small><strong>${c}</strong></div>`).join('')}</div><p><b>Row:</b> ${diff.row} · <b>Output:</b> ${diff.output.join(', ')}</p><p><b>Update order:</b> ${diffEvents.join(' → ') || 'ready'}</p><button id="diff-step">Crank one row</button><button id="diff-square">n²</button><button id="diff-cubic">n³</button><pre>${diff.columns.map((c, i) => `Δ${i}: ${c}`).join('\n')}</pre></section>`); document.querySelector('#diff-step')?.addEventListener('click', () => { const crank = transitionDifference(diff); diff = crank.after; diffEvents = crank.events.map((e) => `Δ${e.sourceOrder}→Δ${e.targetOrder}`); finiteDifference(); }); document.querySelector('#diff-square')?.addEventListener('click', () => { diff = squarePreset(); diffPreset = 'n²'; diffEvents = []; finiteDifference(); }); document.querySelector('#diff-cubic')?.addEventListener('click', () => { diff = cubicPreset(); diffPreset = 'n³'; diffEvents = []; finiteDifference(); }); }
function multiplication() { const c = compare314x27(); shell('Multiplication mechanisms', `<section><h2>314 × 27 = ${c.value}</h2><div class="state-grid"><div><small>Repeated addition</small><strong>${c.repeatedAddition.cranks} cranks</strong><span>one place, no shift</span></div><div><small>Stepped drum</small><strong>${c.steppedDrum.length} digit stages</strong><span>effective steps: ${c.steppedDrum.map((x) => x.effectiveSteps).join(', ')}</span></div><div><small>Pinwheel</small><strong>${c.pinwheel.length} digit stages</strong><span>effective pins: ${c.pinwheel.map((x) => x.effectivePins).join(', ')}</span></div></div><p>These are conceptual operation sequences (GRADE D). The point is to expose crank count, carriage shift, and engagement—not to benchmark machines or claim geometric fidelity.</p></section>`); }
function analytical() { shell('Analytical Engine information flow', `<section><p class="badge">HISTORICAL INFORMATION-FLOW STUDY</p><h2>Cards → control → Mill ↔ Store → output</h2><ol class="timeline">${sampleFlow.map((e) => `<li><b>${e.phase}</b><span>${e.detail}</span></li>`).join('')}</ol><p>“CPU” and “memory” are modern analogies here, not claims that the Analytical Engine had an identical instruction architecture.</p></section>`); }
function curta() { shell('Curta operation path', `<section><p class="badge">GRADE D · OPERATIONAL TEACHING MODEL</p><h2>Setting register → crank → result counter</h2><div class="state-grid"><div><small>Setting register</small><strong>314</strong><span>operand selected by hand</span></div><div><small>Carriage</small><strong>+1 place</strong><span>decimal contribution shifted</span></div><div><small>Revolution counter</small><strong>27</strong><span>repeated crank turns</span></div><div><small>Result counter</small><strong>8478</strong><span>314 × 27</span></div></div><p>Curta is presented as a mechanical algorithm machine: human setting, repeated transfer, place-value shift, and visible counters. This is not a cosmetic full emulator.</p></section>`); }
function about() { shell('About this laboratory', `<section><h2>What is being shown?</h2><p>The project separates mathematical value, mechanical representation, operation phase, event trace, and visualization. Historical claims use sources and evidence grades; simplified models are marked GRADE D.</p><h2>Reality boundary</h2><p>The hand-crank backpropagation exhibit is a counterfactual teaching machine. It does not claim that this browser implementation or its gear metaphors are historical hardware.</p></section>`); }
function continuous() { shell('Continuous mechanical computing', `<section><p class="badge">GRADE D · Euler teaching model</p><h2>Mechanical integrator</h2><p>Input shaft quantity: <b>${integrator.input}</b> · time: <b>${integrator.time.toFixed(2)}</b> · accumulated output: <b>${integrator.output.toFixed(3)}</b></p><button id="integrate">Advance one time step</button><button id="integrate-reset">Reset</button><pre>output += input × step\nstep = ${integrator.step}</pre><p>A real differential analyzer uses coupled continuous mechanisms; this small model shows accumulation and does not reproduce its hardware.</p></section>`); document.querySelector('#integrate')?.addEventListener('click', () => { integrator = integrate(integrator); continuous(); }); document.querySelector('#integrate-reset')?.addEventListener('click', () => { integrator = createIntegrator(1, 0.1); continuous(); }); }
function backprop() { const mapping = mapStageA(phaseMachine.state); shell('Hand-crank backpropagation', `<section><p class="badge">PEDAGOGICAL TRANSLATION · NOT A HISTORICAL MACHINE</p><h2>One phase at a time</h2><div class="state-grid"><div><small>Output</small><strong>${phaseMachine.state.output.toFixed(3)}</strong></div><div><small>Loss</small><strong>${phaseMachine.state.loss.toFixed(4)}</strong></div><div><small>Gradient shafts</small><strong>${mapping.gradientShafts.map((x) => x.toFixed(2)).join(', ')}</strong></div><div><small>Phase</small><strong>${STAGE_A_PHASES[phaseMachine.phaseIndex] ?? 'ready'}</strong></div></div><button id="back-step">Turn one phase</button><button id="back-cycle">Complete cycle</button><button id="back-many">Train 8 cycles</button><button id="back-overshoot">Overshoot preset</button><button id="back-reset">Reset weights</button><p>Learning rate preset: <b>${backPreset}</b></p><pre>${phaseMachine.events.map((e) => e.phase).join('\n') || '—'}</pre><details><summary>Show math</summary><p>y = w₁x₁ + w₂x₂; loss = ½(y − target)². Gradients are read directly from the tested Stage A core.</p></details></section>`); document.querySelector('#back-step')?.addEventListener('click', () => { phaseMachine = stepPhase(phaseMachine); backprop(); }); document.querySelector('#back-cycle')?.addEventListener('click', () => { phaseMachine = runPhaseCycle(phaseMachine); backprop(); }); document.querySelector('#back-many')?.addEventListener('click', () => { for (let i = 0; i < 8; i += 1) phaseMachine = runPhaseCycle(phaseMachine); backprop(); }); document.querySelector('#back-overshoot')?.addEventListener('click', () => { backPreset = 'overshoot'; back = evaluate({ x1: 1, x2: 1, w1: 0, w2: 0, target: 1, learningRate: 1.1 }); phaseMachine = createPhaseMachine(back); backprop(); }); document.querySelector('#back-reset')?.addEventListener('click', () => { backPreset = 'stable'; back = evaluate({ x1: 2, x2: 3, w1: 0, w2: 0, target: 10, learningRate: 0.01 }); phaseMachine = createPhaseMachine(back); backprop(); }); }
function render() { const path = location.hash.slice(1) || '/'; if (path === '/visible-carry') visibleCarry(); else if (path === '/finite-difference') finiteDifference(); else if (path === '/multiplication') multiplication(); else if (path === '/curta') curta(); else if (path === '/analytical-engine') analytical(); else if (path === '/continuous') continuous(); else if (path === '/hand-crank-backprop') backprop(); else if (path === '/about') about(); else overview(); applyTranslations(); }
addEventListener('hashchange', render); addEventListener('keydown', (event) => { if (event.key === ' ' && location.hash === '#/visible-carry') { event.preventDefault(); carryIndex = Math.min(carryIndex + 1, carryTrace.events.length); visibleCarry(); } }); render();
